export default {
    // private
    dashboard: '/dashboard',
    overview: '/overview',
    TMExpand: '/tm',
    TMDev: '/tm/dev',
    TMDevSummary: "/tm/dev/summary",
    TMDevSwitch: "/tm/dev/switch",
    TMQA: '/tm/qa',
    TMQASummary: "/tm/qa/summary",
    TMQASwitch: "/tm/qa/switch",
    TMUAT: '/tm/uat',
    TMUATSummary: "/tm/uat/summary",
    TMUATSwitch: "/tm/uat/switch",
    APExpand: '/appconfig',
    Vault: '/vault',
    Jira: '/jira',
    Pipelines: '/pipelines',
    Connections: '/connnections',
    contacts: '/contacts',
    settings: '/settings',
    environment: '/environment',
    regionUSDev: '/environment/us/dev',
    regionUSQA: '/environment/us/qa',
    // auth
    login: '/login',
    signup: '/signup',
    forgotPassword: '/forgot_password'
};
